forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-apt'
mod 'puppetlabs-nodejs'
mod 'puppetlabs-sqlite'

mod 'mstrauss-editfile',    git: 'https://github.com/mstrauss/puppet-editfile'

mod 'billiam-adminer',    path: 'private/adminer'
mod 'billiam-git',        path: 'private/git'
mod 'billiam-lighttpd',   path: 'private/lighttpd'
mod 'billiam-mysql',      path: 'private/mysql'
mod 'billiam-php5',       path: 'private/php5'
mod 'billiam-postgres',   path: 'private/postgres'
mod 'billiam-prax',       path: 'private/prax'
mod 'billiam-rubygems',   path: 'private/rubygems'
mod 'billiam-site',       path: 'private/site'
mod 'billiam-sqlite3',    path: 'private/sqlite3'